name: keep_serv00_login

on:
  schedule:
    - cron: '10 6 * * 4'  # 每 5 天执行一次
  workflow_dispatch:  # 支持手动执行  

env:
  SSH_ACCOUNTS: ${{ secrets.SSH_ACCOUNTS }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
jobs:
  keep_serv00_login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install jq
        run: sudo apt-get install -y jq 
      
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.2
        with:
          stack: ipv4
        
      - name: Setup IP
        run: |
          sudo curl ip.p3terx.com

      - name: Execute SSH Login Script
        run: |
          echo "$SSH_ACCOUNTS" > accounts.json
          echo "accounts.json 内容："
          chmod +x ./keep_serv00_login.sh 
          ./keep_serv00_login.sh accounts.json "$TG_TOKEN" "$CHAT_ID"
        env:
          PATH: /usr/bin:$PATH
